### ISSUE TITLE
Compiling

### ISSUE THREAD

**Issue by cavery12** [charlesdavid/JEDi#3]
The manual states that only Jama is needed as dependency to compile the source code. I found that several other packages are needed, JFree, and bits.fft.FastCosineTransform2d.  Providing links to these packages may be useful.

**Comment by charlesdavid** [comment]
Yes, need to address: Both Jama and JFree are included as JAR files with JEDi.
The classes from kde like bits.fft are already included in the support package.
We will update the manual to say that both Jama and JFree need to be compiled or the jar files need to be on the classpath.

**Comment by cavery12** [comment]
I was able to compile JEDi on the cluster! I did have to download a new copy of jfreechart because the Args directory was not in the one that is provided with JEDi. In addition the class ChartUtilities.java which is called in JEDi/support/Plot_XY is renamed ChartUtils.java

With this all the drivers were able to compile and I am now going to check that they work

**Comment by charlesdavid** [comment]
That is good. The manual is now updated too.

**Comment by charlesdavid** [comment]
When we do the final release, we will need to be sure that we include the correct versions of all dependencies.
