### ISSUE TITLE
Alignment in HPCA

### ISSUE THREAD

**Issue by cavery12** [charlesdavid/JEDi#6]
We were comparing the AA and HPCA results on the small subsets of residues as discussed and we noticed for a single residue the (taking all modes for both PCAs) the eigenvectors were different. We did not expect this as for a single residue taking all modes (we used subsets of glycine becasue it was the smallest) Of course the whole space was equal, but the working guess as to why the individual vectors were different was because there was an alignment discrepancy between the two PCA types.

We were wondering if you knew off the top of your head how the alignment works for them. Is the whole stucture globally aligned in the pre-processing run, and then the same alignment is used in each PCA type, or is there another alignment in each PCA which is unique to the PCA. For example do you align all the residues locally and individually for HPCA?

**Comment by charlesdavid** [comment]
There are two different alignment schemes for Residue PCA: Global and Local
Local aligns only a single residue to itself.
Global is used for hPCA, where the entire subset is aligned first, no individual residue alignment is done. 
The code is implemented in the Residue PCA class, doLocal and doGlobal methods.
