### ISSUE TITLE
Code Review: Reduced C and Dyn Matrices

### ISSUE THREAD

**Issue by charlesdavid** [charlesdavid/JEDi#7]
I am requesting a code review of the formulae used to compute the reduced c-matrices and reduced dynamical matrices. The two methods are in the class PCA.java: static Matrix get_reduced_C_matrix(Matrix Q), and static Matrix get_reduced_DYN_matrix(Matrix DYN).
The key lines of code are:
double cov = (Q.get(a1, b1) + Q.get(a2, b2) + Q.get(a3, b3));
double dyn = -(DYN.get(a1, b1) + DYN.get(a2, b2) + DYN.get(a3, b3));
The original formulae were written in a vectorized form for Matlab, so I want to be sure that the conversion to the component version here is correct.

**Comment by cavery12** [comment]
The code works fine. I checked the output (from JED) and a reduced Covariance from the MATLAB version of the code and they agree with maximum deviation of 1.0E-6.

**Comment by charlesdavid** [comment]
Great. Is that also the case for the reduced inverse matrices (dynamical)?

**Comment by charlesdavid** [comment]
Thanks for the feedback.
